# Chunky pregeneration metrics.
#
# Short-lived metric: it's meaningful during a generation, and nothing the rest of the time.
name: VaniaMetrics-Chunky
version: ${version}
main: fr.samflix.vaniametrics.module.chunky.ChunkyPaper
api-version: '1.21'
authors: [mc-vania]
description: "Chunky metrics: pregeneration progress."
depend: [VaniaMetrics, Chunky]
